class CountriesInArabic {
  static Map<String, String> names = {
    'World': 'حول العالم',
    'Switzerland': 'سويسرا',
    'Spain': 'اسبانيا',
    'Italy': 'ايطاليا',
    'UAE': 'الامارات العربية المتحدة',
    'France': 'فرنسا',
    'Libya': 'ليبيا',
    'Germany': 'المانيا',
    'Turkey': 'تركيا',
    'USA': 'الولايات المتحدة الامريكية',
    'Iran': 'ايران',
    'Russia': 'روسيا',
    'Brazil': 'البرازيل',
    'UK': 'المملكة المتحدة',
    'Lebanon': 'لبنان',
    'Canada': 'كندا',
    'India': 'الهند',
    'Sweden': 'السويد',
    'Austria': 'استراليا',
    'Israel': 'اسرائيل',
    'Saudi Arabia': 'المملكة العربية السعودية',
    'Japan': 'اليابان',
    'Poland': 'بولندا',
    'Pakistan': 'باكستان',
    'Mexico': 'المكسيك',
    'Denmark': 'الدنمارك',
    'Indonesia': 'اندونيسيا',
    'Qatar': 'قطر',
    'Philippines': 'الفلبين',
    'Egypt': 'مصر',
    'Morocco': 'المغرب',
    'Argentina': 'الارجنتين',
    'Algeria': 'الجزائر',
    'Kuwait': 'الكويت',
    'Bahrain': 'البحرين',
    'Iraq': 'العراق',
    'Oman': 'عمان',
    'Tunisia': 'تونس',
    'Jordan': 'الاردن',
    'Sudan': 'السودان',
    'Syria': 'سوريا',
    'Yemen': 'اليمن',
    'China': 'الصين',
  };
}
